### ISSUE TITLE
Grain (Paddy) Detect from Image

### ISSUE THREAD

**Issue by sumit1212** [ChrisLinSJTU/segmentation-of-powdery-mildew#1]
> Count the number of paddy in a image.
I have create a Model to detect paddy using Tensorflow API Object detection model but it did not work properly, can please help me out how to do that.

![img](https://user-images.githubusercontent.com/28036324/68294867-2059e980-00b7-11ea-941f-8073cc5b2622.png)
![img](https://user-images.githubusercontent.com/28036324/68294897-2f409c00-00b7-11ea-895f-0692d993872b.jpg)
Please tell which approach are you using and technology and some tutorial and blog are you have pls suggest.

Thank you

**Comment by ChrisLinSJTU** [comment]
Sorry for replying too late (。・＿・。)ﾉ.

There is an idea to count rice using deep learning methods- image segmentation method.
First, you can make a small dataset, each sample contains two images, input and output.
input:
![68294867-2059e980-00b7-11ea-941f-8073cc5b2622 (1)](https://user-images.githubusercontent.com/37680743/71159217-32b36f80-2280-11ea-9212-1d8fb4e7d0ca.png)
output: (each white dot indicates a grain)
![微信截图_20191219170129](https://user-images.githubusercontent.com/37680743/71159762-3c89a280-2281-11ea-894a-d479e0dd3e6e.png)

Then, you can use some image segmentation methods, such as FCN, to train your dataset. If the background of the image is not complicated, it may work. And, you can count how many grains in the image.
