### ISSUE TITLE
Question about pre-trained weights

### ISSUE THREAD

**Issue by hedgy123** [ChrisLinSJTU/segmentation-of-powdery-mildew#2]
Hi Chris,

   Thanks for making your code avaialble!   I am new to image processing and DL, so sorry if the questions are simple.  Could you please tell me where the pre-trained weights ('model_weight.h5') came from?  Also, when you say in the comments that you are continuing to train from weights, what does that mean?  Thanks so much!

**Comment by ChrisLinSJTU** [comment]
The file 'model_weight.h5' may be confusing. This file is just used for running the code and avoiding error. 

"continuing to train from weights"  means pre-training. If you have download some pre-trained weights from websites, you can first load it and train you model. Maybe you can refer to Transfer Learning.
